### ISSUE TITLE
Option to enable rounded corners 

### ISSUE THREAD

**Issue by S-Sajith** [mvmike/min-cal-widget#107]
The square corners don't match the aesthetics of all the other  widgets on my home screen , please consider implementing  this feature.

**Comment by mvmike** [comment]
Answering to your email @S-Sajith 

> The screenshots on the playstore show rounded corners on the widget , but when I use the widget I don't see rounded corners , how do I enable it ?

Usually the widget having rounded corners is something managed either at launcher or at OS level. It could be enforced programmatically but it makes more sense to keep it the standard way (as a linear layout withou any shape specificacion) and then allow the launcher/OS to align all existing widgets.

The screenshots in the repo have round corners since the emulator used to take them is an android 12, [when the round corners by default was introduced](https://developer.android.com/about/versions/12/features/widgets).
