### ISSUE TITLE
Reminders and objectives not shown

### ISSUE THREAD

**Issue by zeehio** [mvmike/min-cal-widget#15]
The widget only shows calendar *events*. Google calendar allows to create *reminders* also, but these are not displayed in the widget.

A reminder can be created easily by tapping on the "+" icon on the bottom right of the Google calendar app.

(Feel free to say no if you don't want to support reminders)

**Comment by mvdan** [comment]
Anything that the calendar provider supports could in theory be supported: https://developer.android.com/guide/topics/providers/calendar-provider.html

I see reminders, but not objectives. The latter is probably a Google thing, and not a calendar thing.

**Comment by mvmike** [comment]
After some investigation, it seems there are two types of reminders (it may lead to confusion):

* Associated to an event (to which the calendar provider documentation refers)
* The google calendar app reminder

Since the first option is only an extension of the event instance (that is already shown in the widget) and the second one cannot be queried (as the _objectives_), maybe there is no further improvement in this area that could be applied to the widget.

What do you think, @zeehio?

PS: just to clarify, widget does **not** show calendar events but calendar events _instances_ (for example, one calendar entry that is repeated weekly is only one event with N instances)

**Comment by zeehio** [comment]
Thanks for looking into it and clarifying the terminology.

Given your investigation, closing the issue is the best option. It's kind of sad that there are so many refinements in Google apps and only standard features in AOSP, so these Google reminders can't be queried...

Thanks again and have a wonderful day!
