### ISSUE TITLE
Version 2.11.0  not working

### ISSUE THREAD

**Issue by jaum20** [mvmike/min-cal-widget#170]
After the latest update the widget stopped working on my Xiaomi  Redmi Note10s (Miui 12.5.13). The widget only shows "can’t load widget. Version 2.10.1 is working fine

**Comment by mvmike** [comment]
Hi @jaum20,

Could you please confirm that the version is `2.11.0` and not `2.11.1`? from `2.10.1` to `2.11.0` there are just some graphic adjustments and I can't seem to find any reason why the widget would not load.

Have you tried removing it and adding it again? If, on the other hand, you could provide a logcat of the error that would help a lot

**Comment by mvmike** [comment]
Ok I might have an idea of what could be wrong since it's only failing on Xiaomi devices. Could you please try [this BETA version](https://github.com/mvmike/min-cal-widget/files/11411756/min-cal-widget-BETA.zip) and see if it loads? (it's a different app name `MINCAL_BETA`, so it will be installed as a separate package. Also, it's a zip file since github does not allow direct apk upload, just rename the extension to apk)

There is only a small change compared to the latest release version, so if it loads I know what needs to be changed 🙂

**Comment by E2A4E789A3DCC7236FF998692ADE60E2** [comment]
Can confirm two things:
App version that is listed as 2.11.0 on f-droid doesn't work on my Xiaomi.
The suggested BETA version work fine.

**Comment by 532910** [comment]
Can confirm!
![Screenshot_20230506-141453_Trebuchet.png](https://user-images.githubusercontent.com/14617699/236618151-39cb6666-561f-4704-8521-93e999780fd1.png)

![Screenshot_20230506-141440_F-Droid.png](https://user-images.githubusercontent.com/14617699/236618160-4fd76946-cea5-4bb0-838f-132397395efa.png)

Lineage 18.1 on AOSP 11, OP3T

**Comment by mvmike** [comment]
Found the issue, about to generate a new release now. It seems that some OSs do not implement one method and it was failing only on some devices.

**Comment by mvmike** [comment]
Fixed in [v2.12.2 release](https://github.com/mvmike/min-cal-widget/releases/tag/v2.12.2).

❤️  Thanks all for the bug report and testing, it's really helpful (I can only test in my own device and on studio's AVD where there are only pixels)
