### ISSUE TITLE
nougat

### ISSUE THREAD

**Issue by quartupp** [mvmike/min-cal-widget#179]
Widget loads but its empty no calendar. Forgive my ignorance first time poster long time masterbater

**Comment by mvmike** [comment]
Hi @quartupp, that's actually my fault, let me explain:

When checking android versions used in the google play console, noticed that a couple of people were left with old app versions because of their Nougat operating system version, so I checked if there was any compilation error whilst downgrading the min supported android version and it did not (https://github.com/mvmike/min-cal-widget/commit/6fab912a2343a9494cce0befb8c49372ee5af549 with an associated [job/15245823284](https://github.com/mvmike/min-cal-widget/actions/runs/5625968755/job/15245823284)).

Shortly after that, I discovered that those errors happen at runtime instead of compilation time, reason why I upgraded again the min supported android version to Oreo (8.0) in https://github.com/mvmike/min-cal-widget/commit/aec83b65c4adde7f230520ff291f00b383bcc378

Since I don't plan to support a lower version of android than Oreo because it would require a significant effort on duplicating code for some parts of the app, my suggestion is to rollback to the oldest that was supporting Nougat without it being an error on my side, which would be [v2.6.2](https://github.com/mvmike/min-cal-widget/releases/tag/v2.6.2)
