### ISSUE TITLE
Can't open settings page

### ISSUE THREAD

**Issue by rencornationers** [mvmike/min-cal-widget#193]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/mvmike/min-cal-widget/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/mvmike/min-cal-widget/issues) or [closed](https://github.com/mvmike/min-cal-widget/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I will take the time to fill in all the required details. I understand that the bug report could be dismissed otherwise.
- [X] This issue contains only one bug.

### Describe the bug

There was a gear icon in the upper right corner that led to the settings page, but now it has disappeared. I assumed that perhaps I could find the app in the applications list and go to settings from it, but no. Then I decided to go to the “applications” section from the system settings and find MinCal there, in the hope that there will be the "Open" button or “application settings” like in microG, but still no. Then I re-added the widget thinking that the settings page would immediately open for me, but in the end I simply lost the customized appearance of my widget. I also tried to reinstall the app/use older versions but still nothing.

### Expected Behavior

A gear icon in the upper right corner.

### Affected app version

< 2.12.6

### Device

Realme C3

### Android version

Android 11

### Launcher

Launcher 10 (2.7.48)

### Additional context and screenshots

![Screenshot_2023-10-03-23-28-28-71_74594bd74a0419242537a8d02ba17993](https://github.com/mvmike/min-cal-widget/assets/47507225/0cd21f7f-ed78-4243-95f9-22c2e2353ab1)
![Screenshot_2023-10-03-23-28-40-66_89c3e802f46bca506c06c7d141534caa](https://github.com/mvmike/min-cal-widget/assets/47507225/ffde54fa-d8ed-468e-bb5b-a998129add82)

**Comment by mvmike** [comment]
Hi @rencornationers,

Indeed, [a few releases back](https://github.com/mvmike/min-cal-widget/releases/tag/v2.12.0) I added the [new android widget config feature](https://developer.android.com/develop/ui/views/appwidgets/configuration) that determine a different way on how to access widget configurations (i.e. as described in the link, you should be able to see the option to access configuration both when placing the widget for the first time and when touching & holding it). Could you try doing so? (it should be available from API 28, which is Android 9).

I was already considering adding the option in the configuration to set the config icon visible, but I have doubts since most modern widgets tend to remove config icons and follow the android default guideline 🤷🏻

**Comment by rencornationers** [comment]
Touch & hold does not work in either the system launcher or L10. I already wrote above about installing the widget in L10 for the first time. However, it actually worked in the system launcher 🤔

Launcher 10 has not been updated in recent months. The method of installing a widget for the first time worked earlier, but now for some reason it doesn’t... 🤔

I'll try to reinstall the launcher, maybe that's the problem.

**Comment by rencornationers** [comment]
Reinstalling didn't change anything

**Comment by rencornationers** [comment]
About the tends in modern widgets. How about a compromise solution? Like, even though the gear icon is not displayed, when you click on this corner where it should be located, it will transfer to the settings page.

**Comment by mvmike** [comment]
Even though that sounds like a problem in the launcher rather than the widget, I agree that there is always the potential issue of not being able to access settings, so I'm happy to compromise on an intermediate solution.

I had in mind something slightly different, which would be to have the config icon present by default but be able to hide it in the settings, WDYT?

Meanwhile, you could either downgrade to [the latest version previous to that change](https://github.com/mvmike/min-cal-widget/releases/tag/v2.11.4) or add the widget with a different launcher ([lawnchair](https://github.com/LawnchairLauncher/lawnchair) is working for me, tried in the emulator with different android versions, including 11) and access config from there (app settings are shared regardless of the widget instance)

**Comment by mvmike** [comment]
Just realized that then people that don't have native config access could open settings, hide the icon, close settings and they won't be able to open the settings again (unless they delete app data), which is also not optimal.

I'll go with your approach (clicking on the top right corner always opens the settings, regardless of the icon being present), should be fairly quick to implement 🙂

**Comment by mvmike** [comment]
Fixed in [v2.12.7](https://github.com/mvmike/min-cal-widget/releases/tag/v2.12.7), thanks for raising the issue @rencornationers
