### ISSUE TITLE
v2.16.0 does not refresh date

### ISSUE THREAD

**Issue by Jimadine** [mvmike/min-cal-widget#223]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/mvmike/min-cal-widget/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/mvmike/min-cal-widget/issues) or [closed](https://github.com/mvmike/min-cal-widget/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report could be dismissed otherwise.
- [X] This issue contains only one bug.

### Describe the bug

The latest version updated via F-Droid the other day, and since then the widget emboldened date/underline under the date no longer automatically moves to the current date.

I have noticed that if I update a setting in the app, it forces a refresh and the emboldened date/underline moves to the current day of the week.

### Steps To Reproduce

Turn on display.
Go to home screen.
Look at widget.
Observe emboldened date/underline position.

### Expected Behavior

When the clock strikes midnight, or soon after, the underline/emboldened date should change to the current date. This no longer happens. I am almost certain everything was okay in version 2.15.1.

### Affected app version

2.16.0

### Device

Alcatel 5028Y_EEA

### Android version

10

### Launcher

Lean Launcher 1.1.9

**Comment by mvmike** [comment]
Hi @Jimadine,

Thanks for the report! Indeed, there were some combinations of old android/launchers that were giving problems with updates when upgrading the widget, hence why the `AutoUpdate` is re-added on any user action on the widget (see 2bf5b417df25c7f27b22f40362535f47f65fca22, which was added in [v2.16.0](https://github.com/mvmike/min-cal-widget/releases/tag/v2.16.0)). In this case, even if we can't avoid `AutoUpdate` being unregistered on upgrade, at least it is re-added once there is a single user interaction.

Is this something that happened again on the following day?

**Comment by mvmike** [comment]
As per [documentation](https://developer.android.com/develop/ui/views/appwidgets/advanced#periodic), it is [automatically configured to update every hour](https://github.com/mvmike/min-cal-widget/blob/master/app/src/main/res/xml-v31/month_widget.xml#L13), so regardless of the more frequent custom alarm system that's on top, it should reflect the new day with an hour delay max.

Unfortunately, there isn't much I can do here since I can't replicate it 😞 (most likely it will have something to do with the operating system from this Alcatel device and/or the launcher compatibility with it). My suggestion is, since this issue seems to be triggered by the upgrade (in general, not version specific), to remove and re-add the widget.

**Comment by Jimadine** [comment]
Okay, thank you. I have uninstalled and reinstalled. I will update this thread tomorrow, when I know the outcome.

**Comment by Jimadine** [comment]
The problem is solved - the widget successfully refreshed :thumbsup:. Thanks again for your help :star2:

**Comment by mvmike** [comment]
Thanks for the update, if it happens in the future there is no need to uninstall and reinstall, removing all widget instances from the homescreen and re-adding them should be enough
