### ISSUE TITLE
minSDK to 26 (android 8.0)

### ISSUE THREAD

**Issue by 532910** [mvmike/min-cal-widget#40]
Really this is not an issue.
Could you explain what is the reason for minSDK restriction to 26?
Are you sure it's a must?

If you could make a build of the latest version but without restriction I could test it on android 7.1.

**Comment by mvmike** [comment]
There was a strong need to move to java 8 classes in the `java.time.*` package and stop using Calendar for various calculations in the widget, that's why we upgraded the minSDK (issue #28).

About releasing a version with a lower minSDK, it would require a considerable amount of changes and `java.util.Calendar` is not the way to go (looking forward) since it's a little bit buggy compared to using instants (if you check closed issues, you'll see that few of them were because of this very same reason like #23 or #24), that's why so many projects were/are using joda time.

**Comment by mvdan** [comment]
@mvmike perhaps add a short note about this in the README, since a considerable amount of people are on older versions of Android. Like:

> minSDK: 26 (android 8.0), to use the better `java.time` Java calendar API

**Comment by mvdan** [comment]
One alternative could be https://github.com/JakeWharton/ThreeTenABP, lowering minSdk, but making the APKs quite a bit bigger for the sake of compatibility.

**Comment by mvmike** [comment]
Not sure what to do since it will make builds heavier and less efficient for all android versions if we want to avoid the hassle of maintaining two parallel codebases for the app... even the author states that it's [extremely inefficient](https://github.com/JakeWharton/ThreeTenABP#why-not-use-threetenbp)

**Comment by mvdan** [comment]
True, but note that ThreeTenBP is a *fork* of ThreeTenABP :)

> This library places the timezone information as a standard Android asset and provides a custom loader for parsing it efficiently.

**Comment by mvmike** [comment]
Message added in f321533a67031a1dc23a2b2e525a3cd1b185d94d

**Comment by mvmike** [comment]
@532910 FYI -> bd1ed663b9e220df691d990e5de6baf93668837a and a25daf9f6422017e2619e32a90d56f91b2d7d8c8 moved down the minSDK to 21 (lollipop)
