### ISSUE TITLE
Updating not working

### ISSUE THREAD

**Issue by bushrang3r** [mvmike/min-cal-widget#41]
The widget (1.2.2  from f-droid) isn't updating each day. If I tap on it (which opens the calendar app) and then go back to the home screen, it updates (highlights today's date). It was working fine for me in all versions before this one.

Android 9.0
Galaxy NOTE 4
Resurrection Remix Rom

**Comment by mvmike** [comment]
Update rate is managed by the system, not the widget itself. Although [it's configured to be updated every 30mins](https://github.com/mvmike/min-cal-widget/blob/f6c7e60e37620b970c2f13c0e20fea579662cf75/app/src/main/res/xml/widget_info.xml#L10) (the minimum period according to [android documentation](https://developer.android.com/reference/android/appwidget/AppWidgetProviderInfo#updatePeriodMillis)), it is not guaranteed to occur exactly on time, so it might differ a bit.

In any case, tested in different devices and, considering this potential small delay, the widget is being updated consistently. On the other hand, update rate/config hasn't changed in the widget since the first versions, could it be something related with your OS that's limiting background processes?

**Comment by bushrang3r** [comment]
Yes, the widget was updating reliably before with Oreo.  I'm now using 9.0 (Pie). 
By 'not updating' I mean it sometimes goes 4 or 5 days without updating and so it's still highlighting the date from 4-5 days ago. 
I have turned off battery optimization for the app but I don't think that would be stopping it from updating for that amount of time. I'll test it for a bit longer.

**Comment by mvmike** [comment]
Also on android 9 and i didn't notice any difference coming from 8.1

Let us know if it this persists

**Comment by bushrang3r** [comment]
![image_2019-04-02_09-51](https://user-images.githubusercontent.com/5970120/55399201-70068e80-5585-11e9-85e8-d645dff77b7f.jpg)

**Comment by mvmike** [comment]
Been checking how to solve this and there is no way to enforce the widget update, it's the system/OS who's handling the call to the `AppWidgetProvider` API, specifically the `onUpdate` method (the one used for updating the current date amongst other stuff).

I'd really like to be more of help, but it seems something related to your current OS that can not be tackled from our end :(

Will close the issue but feel free to reopen it if you have any idea on how to do solve this

**Comment by mvdan** [comment]
@bushrang3r as a random idea, try removing the widget and adding it again.

**Comment by bushrang3r** [comment]
Thanks @mvdan
Removing and re-adding the widget seems to have fixed the problem.
