### ISSUE TITLE
start improvment

### ISSUE THREAD

**Issue by 532910** [mvmike/min-cal-widget#47]
Every time I reboot the phone min-cal-widget takes a lot of time to start. As I suspect it's not due to min-cal issues, but due to calendar provider DAVx⁵.

If I'm right, it can be improved: The calendar itself should shown as fast as possible, and symbols (task) should be loaded in background ans shown as they become ready.

![image](https://user-images.githubusercontent.com/14617699/69744471-496b1880-1151-11ea-8464-91906a16cf1a.png)

**Comment by mvmike** [comment]
After investigating a bit, it seems there is no way to know when the widget is being drawn because the phone is starting.

Will consider adding a very small timeout for reading the calendar instances and using a completableFuture or similar in case the timeout is reached , since drawing and getting the system information can't be decoupled.

**Comment by 532910** [comment]
Why do you need to "know when the widget is being drawn" and "decouple drawing and getting the system information"?

Is it possible to draw the calendar without accessing calendar provider. And draw task symbols after the previous action.

**Comment by mvmike** [comment]
Indeed, it can be drawn without the calendar provider information. What i meant before is that the system calls only one function for everything, both drawing the widget and getting the provider info, and the thread is going to be blocked until everything finishes, hence why i was mentioning the possibility to use a java Future.

In other words, the internal logic would be something like:

1 - get provider info with a small timeout
2 - if timeout is reached, draw without instances and create a future task to add them, behave normally otherwise

The reason why we don't go with the future always it's because adding the instances means redrawing some part of the widget, which is less efficient and not necessary in most occasions

**Comment by mvmike** [comment]
Seems that fetching instances is not the issue, although the work has been commited in bea9c0952a82872d0119646ca34b209f639663f4 since it was already done (does not hurt, might be useful in some scenarios).

After adding some loggers, drawing the widget takes around ~10ms (in the emulator) to be drawn, which can almost be neglected, and there is no way to control when the operating system gives priority to this particular widget instance.

Maybe the feeling of speed in other widgets is because they draw a static image instead of having a spinner while waiting, but we don't have that option since we rely on system's date.
